# Generated by Django 5.0.2 on 2024-03-14 18:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('industries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), null=True, size=None)),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), null=True, size=None)),
                ('employee_range', models.CharField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage',
            },
        ),
        migrations.CreateModel(
            name='OrganizationData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(null=True)),
                ('website_url', models.CharField(null=True)),
                ('linkedin_url', models.CharField(null=True)),
                ('twitter_url', models.CharField(null=True)),
                ('founded_year', models.IntegerField(null=True)),
                ('location', models.CharField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadgen.usage')),
            ],
            options={
                'db_table': 'organization_data',
            },
        ),
    ]
