# Generated by Django 5.0.2 on 2024-03-18 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0004_usage_designations_usage_keyword_usage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(null=True)),
                ('designation', models.CharField(null=True)),
                ('linkedin_url', models.CharField(null=True)),
                ('twitter_url', models.CharField(null=True)),
                ('org_name', models.CharField(null=True)),
                ('org_url', models.CharField(null=True)),
                ('location', models.CharField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadgen.usage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads_data',
            },
        ),
    ]
